### PR TITLE
Added DeleteTemplate functions to stores

### LINKED ISSUE #7: Add DeleteTemplate function to InMemoryStore

### PR DESCRIPTION
**Pull request by captainsafia**
Closes #7.

giphy-11

cc/ @rgbkrk

### CODE REVIEW

**Comment by captainsafia** [comment]
@rgbkrk — I think this is good to merge. Let me know.

**Comment by rgbkrk** [comment]
Since the mongo stuff is in this code base, you'll want to add that too. We can merge for now though since there shouldn't be any users of this.

**Comment by captainsafia** [comment]
The `DeleteTemplate` function is already in the `MongoStore` so I had to add it to this to maintain consistency across the API.

**Comment by rgbkrk** [comment]
Ahhhhhh

**Comment by rgbkrk** [comment]
:shipit:

**Pull request merged**
